#pragma once

const char JS_UPDATE_MQTT[] PROGMEM = ""
"const mqttElem = document.getElementById('mqtt_status');"
"let mqttLastText = mqttElem.innerHTML;"
"function updateMQTTStatus() {"
    "fetch('/mqttStatus')"
        ".then(response => response.json())"
        ".then(data => {"
            "if(mqttLastText!==data.status) {"
                "mqttElem.innerHTML = data.status;"
                "mqttElem.classList.toggle('red');"
                "mqttElem.classList.toggle('green');"
                "mqttLastText = data.status;"
            "}"
        "}"
    ");"
"}"
"updateMQTTStatus();"
"setInterval(updateMQTTStatus, 1000);";

const char JS_UPDATE_WIFI[] PROGMEM = ""
"const wifiElem = document.getElementById('wifi_status');"
"let wifiLastText = wifiElem.innerHTML;"
"function updateWifiStatus() {"
    "fetch('/wifiStatus')"
        ".then(response => response.json())"
        ".then(data => {"
            "if(wifiLastText!==data.status) {"
                "wifiElem.innerHTML = data.status;"
                "wifiElem.classList.toggle('red');"
                "wifiElem.classList.toggle('green');"
                "wifiLastText = data.status;"
            "}"
        "}"
    ");"
"}"
"updateWifiStatus();"
"setInterval(updateWifiStatus, 1000);";

const char HTML_LANDING_PAGE[] PROGMEM = ""
"<!DOCTYPE html>"
"<html lang=\"en\">"
  "<head>"
    "<meta charset=\"UTF-8\" />"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
    "<title>Captive portal</title>"
    "<link rel=\"stylesheet\" href=\"landingPage.css\" />"
  "</head>"
  "<body>"
    "<div class=\"content\">"
      "<h1 class=\"page-title\">Hub configuration</h1>"
      "<p>Wifi Status:"
        "<span id=\"wifi_status\" class=\"red upper bold\">not connected</span>"
      "</p>"
      "<p>MQTT Status:"
        "<span id=\"mqtt_status\" class=\"red upper bold\">not connected</span>"
      "</p>"
      "<button onclick=\"window.location.href = '/wifi'\">Configure WiFi</button"
      "><button onclick=\"window.location.href = '/mqtt'\">Configure MQTT</button>"
    "</div>"
    "<script src=\"updateWiFi.js\"></script>"
    "<script src=\"updateMQTT.js\"></script>"
  "</body>"
"</html>";

const char HTML_WIFI[] PROGMEM = ""
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
    "<meta charset=\"UTF-8\" />"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
    "<title>Captive portal</title>"
    "<link rel=\"stylesheet\" href=\"formPage.css\" />"
"</head>"
"<body>"
"<div class=\"content\">"
    "<h1 class=\"page-title\">WiFi configuration</h1>"
    "<form method=\"post\" action=\"/wifi\">"
        "<input type=\"text\" name=\"ssid\" placeholder=\"SSID\" />"
        "<input type=\"password\" name=\"password\" placeholder=\"Password\"/>"
        "<button type=\"submit\">Connect</button>"
    "</form>"
"</div>"
"</body>"
"</html>";

const char HTML_MQTT[] PROGMEM = ""
"<!DOCTYPE html>"
"<html lang=\"en\">"
  "<head>"
    "<meta charset=\"UTF-8\" />"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
    "<title>MQTT Configuration</title>"
    "<link rel=\"stylesheet\" href=\"formPage.css\" />"
  "</head>"
"<body>"
"<div class=\"content\">"
    "<h1 class=\"page-title\">MQTT configuration</h1>"
    "<form method=\"post\" action=\"/mqtt\">"
    "<label for=\"server\">Server</label>"
    "<input type=\"text\" name=\"server\" placeholder=\"MQTT Server\" />"
    "<label for=\"server\">Username</label>"
    "<input type=\"text\" name=\"user\" placeholder=\"MQTT User\" />"
    "<label for=\"server\">Password</label>"
    "<input type=\"password\" name=\"password\" placeholder=\"Password\" />"
    "<button type=\"submit\">Connect</button>"
    "</form>"
"</div>"
"</body>"
"</html>";

const char CSS_LANDING_PAGE[] PROGMEM = ""
"body {"
  "box-sizing: border-box;"
  "margin: 0;"
  "padding: 0;"
  "font-family: sans-serif;"
  "background-color: #0a1b2c;"
  "color: white;"
"}"
".content {"
  "font-family: sans-serif;"
  "margin: 0 auto;"
  "width: 80%;"
  "display: flex;"
  "align-items: center;"
  "flex-direction: column;"
"}"
".green {"
  "color: green;"
"}"
".red {"
  "color: red;"
"}"
".upper {"
  "text-transform: uppercase;"
"}"
".bold {"
  "font-weight: bold;"
"}"
"button {"
  "width: 16ch;"
  "font-size: 1.8rem;"
  "margin-top: 20px;"
  "padding: 8px20px;"
  "background-color: #3089db;"
  "color: #0a1b2c;"
  "font-weight: bold;"
  "border: none;"
  "border-radius: 5px;"
  "cursor: pointer;"
"}"
".page-title {"
  "font-size: 2.5rem;"
  "margin-bottom: 20px;"
  "color: #c1dcf4;"
"}";

const char CSS_FORM[] PROGMEM = ""
"body {"
  "box-sizing: border-box;"
  "margin: 0;"
  "padding: 0;"
  "font-family: sans-serif;"
  "background-color: #0a1b2c;"
  "color: white;"
"}"
".content {"
  "font-family: sans-serif;"
  "margin: 0 auto;"
  "width: 80%;"
  "display: flex;"
  "align-items: center;"
  "flex-direction: column;"
"}"
"button {"
  "width: 16ch;"
  "font-size: 1.8rem;"
  "margin-top: 20px;"
  "padding: 8px20px;"
  "background-color: #3089db;"
  "color: #0a1b2c;"
  "font-weight: bold;"
  "border: none;"
  "border-radius: 5px;"
  "cursor: pointer;"
"}"
".page-title {"
  "font-size: 2.5rem;"
  "margin-bottom: 20px;"
  "color: #c1dcf4;"
"}"
"form {"
  "display: flex;"
  "flex-direction: column;"
  "width: 100%;"
"}";
